### ISSUE TITLE
Getting "The version does not exist"

### ISSUE THREAD

**Issue by MasverseChan** [zy-linn/serverless-huawei-functions#1]
Node
-  v20.11.0

Serverless :
- Framework Core: 3.38.0 (local) 3.38.0 (global)
- Plugin: 7.2.3
- SDK: 4.5.1

serverless.yml 

```
service: testfunctionGraph

frameworkVersion: "3"
configValidationMode: 'off'
provider: 
  name: huawei
  credentials: ~/.fg/credentials
  runtime: Node.js14.18 
  region: ap-southeast-3	

plugins:
  - serverless-huawei-functions

functions:
  test-functin:
    handler: index.handler
    description: Huawei Serverless Cloud Function
```

Error 
```
nodesdk:$c:2 Some error found: {
  data: { error_code: 'FSS.1052', error_msg: 'The version does not exist.' },
  status: 404,
  headers: {
    server: 'CloudWAF',
    date: 'Tue, 26 Mar 2024 01:48:51 GMT',
    'content-type': 'application/json',
    'content-length': '74',
    connection: 'keep-alive',
    'set-cookie': [
      'HWWAFSESID=fda8576c8a7b586cb5; path=/',
      'HWWAFSESTIME=1711417730299; path=/'
    ],
    'x-request-id': '019d9e291dc7061e487b714ba49d9da3'
  },
  message: 'Request failed with status code 404',
  requestId: '019d9e291dc7061e487b714ba49d9da3',
  config: {
    url: '/v2/366475b35129473fbe7511533305fef2/fgs/functions/urn:fss:ap-southeast-3:366475b35129473fbe7511533305fef2:function:default:maschain-billing-schedules-dev-test-functin:latest/config',
    method: 'get',
    headers: {
      Accept: 'application/json',
      'X-Project-Id': '366475b35129473fbe7511533305fef2',
      'X-Sdk-Date': '20240326T014859Z',
      host: 'functiongraph.ap-southeast-3.myhuaweicloud.com',
      Authorization:  XXXXXXXXX
      'User-Agent': 'huaweicloud-usdk-nodejs/3.0',
      'Content-Type': 'application/json'
    },
    proxy: false,
    params: {},
    baseURL: 'https://functiongraph.ap-southeast-3.myhuaweicloud.com',
    transformRequest: [ [Function (anonymous)] ],
    transformResponse: [ [Function (anonymous)] ],
    paramsSerializer: [Function: paramsSerializer],
    timeout: 0,
    adapter: [Function (anonymous)],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: Infinity,
    maxBodyLength: Infinity,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    data: undefined
  }
}
```
